### Sign Up User

POST http://localhost:6000/api/user/signUp
content-type: application/json

{
    "username": "Kristi3",
    "password": "Superhemligt",
    "email": "kristi3@gmail.com",
    "deliveryAddress": "Okergatan 3",
    "bad": "cat"
}

### Login User

POST http://localhost:6000/api/user/loginUser
content-type: application/json

{
    "username": "Kristi3",
    "password": "Superhemligt"
}

### 
GET http://localhost:6000/api/user/info
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktyaXN0aTMiLCJpYXQiOjE2NjYyNjg0NDQsImV4cCI6MTY2NjM1NDg0NH0.C9ZpOeM5MP0j7eAQkpXk3kRx29BPiYxZAK_sisnQqLI