version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "${MONGO_DB_BACKEND_PORT}:${MONGO_DB_BACKEND_PORT}"
    environment:
      - MONGODB_URL=${MONGODB_URL}

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        APP_WEBSHOP_API: ${APP_WEBSHOP_API}
    ports:
      - "${MONGO_DB_FRONTEND_PORT}:${MONGO_DB_FRONTEND_PORT}"

  db_webshop:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    container_name: ${MONGO_DB_CONTAINER_NAME}
    volumes:
      - /data/${MONGO_DB_CONTAINER_NAME}
